# Generated by Django 4.1.2 on 2022-10-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
